import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@styles/globals.css";

export const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "600", "700", "900"],
  adjustFontFallback: true, // default is "Arial" if set to false
  fallback: ["system-ui", "sans-serif"], // customize fallback stack
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
